#!/usr/bin/python
# -*- coding: UTF-8 -*-
def primefunc(x):
    for i in range (2, x):
	if x % i ==0:
            return 'it is not a prime'
	    break
    else:
        return 'it is a prime'
number = input("please input number: ")
print primefunc(number)    
